### ISSUE TITLE
Does not compile in Ubuntu 14.10

### ISSUE THREAD

**Issue by hixus** [mschwartz/SilkJS#41]
I followed the instructions in Silkjs.net but got error. Heres the output:

Checked out revision 1501.
make[2]: Leaving directory '/home/carlo/src/SilkJS/src/v8-read-only'
make[2]: Entering directory '/home/carlo/src/SilkJS/src/v8-read-only'
make[3]: Entering directory '/home/carlo/src/SilkJS/src/v8-read-only/out'
  CXX(target) /home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/once.o
  CXX(target) /home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/conversions.o
In file included from ../src/utils.h:36:0,
                 from ../src/conversions.h:31,
                 from ../src/conversions-inl.h:40,
                 from ../src/conversions.cc:32:
../src/scanner.h: In member function ‘void v8::internal::Scanner::Init()’:
../src/checks.h:251:22: error: typedef ‘**StaticAssertTypedef__450’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef**, **LINE**)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(**StaticAssertTypedef**, **LINE**)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/scanner.h:450:5: note: in expansion of macro ‘STATIC_ASSERT’
     STATIC_ASSERT(kCharacterLookaheadBufferSize == 1);
     ^
  CXX(target) /home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/preparse-data.o
In file included from ../src/hashmap.h:32:0,
                 from ../src/preparse-data.h:32,
                 from ../src/preparse-data.cc:31:
../src/preparse-data.cc: In member function ‘virtual void v8::internal::FunctionLoggingParserRecorder::LogMessage(int, int, const char_, const char_)’:
../src/checks.h:251:22: error: typedef ‘**StaticAssertTypedef__69’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef**, **LINE**)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(**StaticAssertTypedef**, **LINE**)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/preparse-data.cc:69:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(PreparseDataConstants::kMessageStartPos == 0);
   ^
../src/checks.h:251:22: error: typedef ‘**StaticAssertTypedef__71’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef**, **LINE**)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(**StaticAssertTypedef**, **LINE**)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/preparse-data.cc:71:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(PreparseDataConstants::kMessageEndPos == 1);
   ^
../src/checks.h:251:22: error: typedef ‘**StaticAssertTypedef__73’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef**, **LINE**)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(**StaticAssertTypedef**, **LINE**)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/preparse-data.cc:73:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(PreparseDataConstants::kMessageArgCountPos == 2);
   ^
../src/checks.h:251:22: error: typedef ‘**StaticAssertTypedef__75’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef**, **LINE**)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(**StaticAssertTypedef**, **LINE**)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/preparse-data.cc:75:3: note: in expansion of macro ‘STATIC_ASSERT’
   STATIC_ASSERT(PreparseDataConstants::kMessageTextPos == 3);
   ^
cc1plus: all warnings being treated as errors
tools/gyp/preparser_lib.target.x64.mk:112: recipe for target '/home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/conversions.o' failed
make[3]: **\* [/home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/conversions.o] Error 1
make[3]: **\* Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
tools/gyp/preparser_lib.target.x64.mk:112: recipe for target '/home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/preparse-data.o' failed
make[3]: **\* [/home/carlo/src/SilkJS/src/v8-read-only/out/x64.release/obj.target/preparser_lib/src/preparse-data.o] Error 1
make[3]: Leaving directory '/home/carlo/src/SilkJS/src/v8-read-only/out'
Makefile:183: recipe for target 'x64.release' failed
make[2]: **\* [x64.release] Error 2
make[2]: Leaving directory '/home/carlo/src/SilkJS/src/v8-read-only'
Makefile:85: recipe for target 'v8-read-only/out/x64.release/obj.target/tools/gyp/libv8_base.a' failed
make[1]: **\* [v8-read-only/out/x64.release/obj.target/tools/gyp/libv8_base.a] Error 2
make[1]: Leaving directory '/home/carlo/src/SilkJS/src'
Makefile:34: recipe for target 'install' failed
make: **\* [install] Error 2

**Comment by volonterx** [comment]
Same problem on 14.04.3. 

I've tried to install libv8-dev package. It did not help me (cause of version, I think)

Fetched 1,247 kB in 0s (2,395 kB/s)   
Selecting previously unselected package libv8-3.14.5.
(Reading database ... 101006 files and directories currently installed.)
Preparing to unpack .../libv8-3.14.5_3.14.5.8-5ubuntu2_amd64.deb ...
Unpacking libv8-3.14.5 (3.14.5.8-5ubuntu2) ...
Selecting previously unselected package libv8-dev.
Preparing to unpack .../libv8-dev_3.14.5.8-5ubuntu2_amd64.deb ...
Unpacking libv8-dev (3.14.5.8-5ubuntu2) ...
Setting up libv8-3.14.5 (3.14.5.8-5ubuntu2) ...
Setting up libv8-dev (3.14.5.8-5ubuntu2) ...

**Comment by volonterx** [comment]
Output: 


myappnew@solr:~/application/releases/20151102204630$ gem install libv8 -v '3.11.8.4'
Building native extensions.  This could take a while...
ERROR:  Error installing libv8:
        ERROR: Failed to build gem native extension.

/home/myappnew/.rvm/rubies/ruby-1.9.3-p392/bin/ruby -r ./siteconf20151103-16909-1e7tsqc.rb extconf.rb
creating Makefile
Using compiler: /usr/bin/g++
In file included from ../src/utils.h:36:0,
                 from ../src/conversions.h:31,
                 from ../src/conversions-inl.h:40,
                 from ../src/conversions.cc:32:
../src/scanner.h: In member function ‘void v8::internal::Scanner::Init()’:
../src/checks.h:251:22: error: typedef ‘__StaticAssertTypedef__450’ locally defined but not used [-Werror=unused-local-typedefs]
     SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
                      ^
../src/checks.h:241:39: note: in definition of macro ‘SEMI_STATIC_JOIN_HELPER’
 #define SEMI_STATIC_JOIN_HELPER(a, b) a##b
                                       ^
../src/checks.h:251:5: note: in expansion of macro ‘SEMI_STATIC_JOIN’
     SEMI_STATIC_JOIN(__StaticAssertTypedef__, __LINE__)
     ^
../src/checks.h:283:30: note: in expansion of macro ‘STATIC_CHECK’
 #define STATIC_ASSERT(test)  STATIC_CHECK(test)
                              ^
../src/scanner.h:450:5: note: in expansion of macro ‘STATIC_ASSERT’
     STATIC_ASSERT(kCharacterLookaheadBufferSize == 1);
     ^
cc1plus: all warnings being treated as errors
make[1]: *** [/home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o] Error 1
make: *** [x64.release] Error 2
GYP_GENERATORS=make \
        build/gyp/gyp --generator-output="out" build/all.gyp \
                      -Ibuild/standalone.gypi --depth=. \
                      -Dv8_target_arch=x64 \
                      -S.x64 -Dhost_arch=x64
make[1]: Entering directory '/home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out'
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/allocation.o
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/atomicops_internals_x86_gcc.o
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum.o
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/bignum-dtoa.o
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/cached-powers.o
  CXX(target) /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out/x64.release/obj.target/preparser_lib/src/conversions.o
make[1]: Leaving directory '/home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4/vendor/v8/out'

extconf failed, exit code 2

Gem files will remain installed in /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/gems/libv8-3.11.8.4 for inspection.
Results logged to /home/myappnew/.rvm/gems/ruby-1.9.3-p392@myappnew/extensions/x86_64-linux/1.9.1/libv8-3.11.8.4/gem_make.out

**Comment by volonterx** [comment]
Check this issue: 
https://code.google.com/p/v8/issues/detail?id=2149
https://codereview.chromium.org/69413002
